node {
    try {
    stage('GIT Checkout') {
        checkout scm: [
            $class: 'GitSCM',
            branches: [[name: '*/main']],
            userRemoteConfigs: [[url: 'https://github.com/OT-MICROSERVICES/salary-api.git']]
        ]
    }
    
    stage('Compile') {
        sh 'mvn clean compile'
    }
    stage('Static Code Analysis') {
        withSonarQubeEnv(installationName: 'sq1') { 
          sh './mvnw org.sonarsource.scanner.maven:sonar-maven-plugin:3.9.0.2155:sonar'
        }
    }    
    } catch (e) {
        echo 'Static Code Analysis Failed'
        cleanWs()
        throw e
    } finally {
        def currentResult = currentBuild.result ?: 'SUCCESS'
        if ((currentResult == 'UNSTABLE')||(currentResult == 'ABORTED')) {
            cleanWs()
        }
    }
}
